# This job needs 1 compute node with 1 processor per node.
#PBS -l nodes=1:ppn=1
# It should be allowed to run for up to x hour.
#PBS -l walltime=10:00:00
# Name of job.
#PBS -N oblock
# Join STDERR TO STDOUT.  (omit this if you want separate STDOUT AND STDERR)
#PBS -j oe   
# Send me mail on job start, job end and if job aborts
#PBS -M oweenm@gmail.com
#PBS -m bea

cd /users/o/m/omyers/datasphere/PeriodicPotential
echo "This is myjob running on " `hostname`
python lookdat.py
