# This job needs 1 compute node with 1 processor per node.
#PBS -l nodes=1:ppn=1
# It should be allowed to run for up to x hour.
#PBS -l walltime=30:00:00
# Name of job.
#PBS -N ECtec2DB_split
# Join STDERR TO STDOUT.  (omit this if you want separate STDOUT AND STDERR)
#PBS -j oe   
# Send me mail on job start, job end and if job aborts

cd /users/o/m/omyers/datasphere/ECproject/HeatMapBif/
echo "This is myjob running on " `hostname`
