# This job needs 1 compute node with 1 processor per node.
#PBS -l nodes=1:ppn=1
# It should be allowed to run for up to x hour.
#PBS -l walltime=1:00:00
# Name of job.
#PBS -N initab
# Join STDERR TO STDOUT.  (omit this if you want separate STDOUT AND STDERR)
#PBS -j oe   

cd /users/o/m/omyers/datasphere/ECproject/HeatMapBif/TryJobArr
echo "This is myjob running on " `hostname`
python tryjobarr.py --dir $PBS_ARRAYID"ha.txt"
if [ $PBS_ARRAYID -eq 3 ]; then
    echo "we work"
fi
