# This job needs 1 compute node with 1 processor per node.
#PBS -l nodes=1:ppn=1
# It should be allowed to run for up to x hour.
#PBS -l walltime=30:00:00
# Name of job.
#PBS -N takelast_cot
# Join STDERR TO STDOUT.  (omit this if you want separate STDOUT AND STDERR)
#PBS -j oe   

cd /users/o/m/omyers/datasphere/ECproject/HeatMapBif/Continue
echo "This is myjob running on " `hostname`
python takelast.py --dir Block_Tue_Mar_26_130102_2013_ -n 1
